 development:
   adapter: mysql2
   encoding: utf8
   database: shopies_development
   username: tunhanmra
   password: tunhanmra
   port: 8889
   host: 127.0.0.1
   variables:
     sql_mode: TRADITIONAL
 test:
   adapter: mysql2
   encoding: utf8
   database: shopies_test
   username: tunhanmra
   password: tunhanmra
   port: 8889
   host: 127.0.0.1
   variables:
     sql_mode: TRADITIONAL

 production:
   adapter: mysql2
   database: shopies_production
   username: prod
   password: prodpwd
